knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: created_at    # sort field query parameter name
        sort_direction_name: desc # sort direction query parameter name
        distinct: false                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: /PublicBlog/_pagination.html.twig
